Prevent dispensers from bonemealing plants when disable-bonemeal is true
TheBusyBiscuit/ExoticGarden pull request #203
Opened 2021-04-22 14:15 UTC by NCBPFluffyBear

This fix prevents dispensers from bypassing EG bonemealing when it is disabled.

2021-04-22 14:32 UTC, WalshyDev commented
I feel like this should really be fixed in Spigot. BlockFertilizeEvent is made for this... I feel like a proper fix should be PR'd there or at least an issue created (not sure if one exists already)

2021-04-26 09:01 UTC, TheBusyBiscuit requested changes
As Walshy already pointed out - this is such a bullshit thing to do, the `BlockFertilizeEvent` should really just be fixed within Spigot itself...

2021-04-26 09:01 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/exoticgarden/listeners/PlantsListener.java
> +        ItemStack bonemeal = e.getItem();
This shouldn't really be named `bonemeal` here. We don't know if it is bone meal yet.

2021-04-26 09:01 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/exoticgarden/listeners/PlantsListener.java
> +    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
Why HIGHEST? :NotLikeThis:

2021-04-28 09:07 UTC, WalshyDev commented
Just looked at Jira, there is an issue for this - https://hub.spigotmc.org/jira/browse/SPIGOT-6020

Also an open PR (made by the guy who commented): https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/826/overview

No idea if TheCreeperCow saw this PR but that's fantastic timing

2021-05-03 08:42 UTC, WalshyDev commented
> Just looked at Jira, there is an issue for this - https://hub.spigotmc.org/jira/browse/SPIGOT-6020
> 
> Also an open PR (made by the guy who commented): https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/826/overview
> 
> No idea if TheCreeperCow saw this PR but that's fantastic timing

Merged - https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7ea8b96b4a9a168723d1eb109c5abc6fe91b78d6

2021-05-03 10:19 UTC, closed without merging